config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root to: "home#index"
  devise_for :users
  match "/home/add_user", :to => "home#add_user", :via => ["get","post"]
  match "/secret_code/index", :to => "secret_code#index", :via => ["get"]
  match "/secret_code/add", :to => "secret_code#add", :via => ["post"]
  resources :secret_code
end

app/models/secret_code.rb
class SecretCode < ActiveRecord::Base
	has_one :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
belongs_to :secret_code
validates :secret_code_id, presence: true
validates :secret_code_id, uniqueness: true
validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  private
#def after_sign_in_path_for(resource)
#secret_code_index_path
#end

def authenticate_user!
if user_signed_in? and current_user.role=='admin'
super
puts"--current_user.role---#{current_user.role}--------"
else
#redirect_to home_index_path, :notice => 'Not authenticate user!'
#puts"--current_user.role---#{current_user.role}--------"
end
end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :authenticate_user!, only: [:add_user]
  def index
  end
  def add_user
  	@user_all = User.where("role='user'")
if params[:email] and params[:code_id].to_i!=0
	@find_email = User.find_by_email(params[:email])
	if @find_email
		redirect_to home_add_user_path,:alert => ' Email has already been taken!!!'
	else

@user = User.create(email: "#{params[:email]}",
password: "password",
password_confirmation: "password",
secret_code_id: params[:code_id],
role:'user'              
)
@user.save!
@c = SecretCode.find_by_id(params[:code_id])
@c.update_attributes(:user_id=>@user.id)
end
elsif params[:email] and params[:code_id].to_i==0
redirect_to home_add_user_path,:alert => 'Please create secret code!!!'
end

  end


  private
def authenticate_user!
if user_signed_in? and current_user.role=='admin'
super
else
redirect_to home_index_path, :alert => 'Unauthorized access!!!'
end
end
end

app/controllers/secret_code_controller.rb
class SecretCodeController < ApplicationController
before_action :authenticate_user!
def index
	@code = SecretCode.all
end
def add
	params[:no_of_code].to_i.times do |no|
		@code = SecureRandom.hex(3)
		SecretCode.create(code: "#{@code}", user_id: 0,created_by:current_user.id)
    end
redirect_to secret_code_index_path
end
private
def authenticate_user!
if user_signed_in? and current_user.role=='admin'
super
else
redirect_to home_index_path, :alert => 'Unauthorized access!!!'
end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/secret_code_helper.rb
module SecretCodeHelper
end

app/views/home/add_user.html.erb
<div class="jumbotron">
    <div class="container">
    	&nbsp;&nbsp;&nbsp;
<%= link_to "Add Secret Code's", secret_code_index_path, class: 'btn btn-danger  btn-lg' %>
<%= form_for('user', as: 'user', url: home_add_user_path) do |f| %>
<h2>Add User!</h2> 
<div class="form-group">
<div align="left" style="padding-left:15px;"><b>Email</b></div>
<div class="col-xs-12 col-sm-6 col-md-12 col-lg-6"><input type="email" name="email" class="form-control" placeholder="Email" value="" required></div> 
</div>
</br>
<div class="form-group">
<div align="left" style="padding-left:15px;"><b>Secret Code</b></div>
<%@code = SecretCode.find_by_user_id(0)
if @code!=nil
	@code_id = @code.id
	@code = @code.code
	
else
	@code = ""
	@code_id = 0
end%>
<input type="hidden" name="code_id" value="<%=@code_id%>">
<input type="hidden" name="code" value="<%=@code%>">
<div class="col-xs-12 col-sm-6 col-md-12 col-lg-6"><input type="text" name="code" class="form-control" placeholder="Secret Code" value="<%=@code%>" disabled></div> 
</div>
</br></br>
<%= f.submit "Save" , class: 'btn btn-success btn-lg'%>&nbsp;&nbsp;&nbsp;

<%end%>
</br></br>

<table width="100%" align="center" border='1px'  class="table table-bordered table-admin">
<thead>
<tr class="header_bg">
<th>S.No</th>
<th>Email</th>
<th>User Secret Code</th>

</tr>
</thead>

<tbody>
<%
i=1
@user_all.each do |u| 
if u.secret_code_id.to_i!=0
@code = SecretCode.find_by_id(u.secret_code_id).code
else
@code= "--"
end
%>
<tr class="odd">
<td width="1%" align="center"><%= i %></td>
<td width="12%" style="word-break: break-all;"><%= u.email %></td> 
<td width="12%" style="word-break: break-all;"><%= @code %></td>


</tr>
<%i=i+1 
end %>
</tbody>
</table>

    	</div>
  </div>

app/views/home/index.html.erb
<% if user_signed_in? and current_user.role=='admin' %>
<div class="jumbotron">
    <div class="container">
    	</br></br>
    	<%add_user_path = "/home/add_user"%>
<%= link_to 'Add User', add_user_path, class: 'btn btn-success btn-lg' %>
&nbsp;&nbsp;&nbsp;
<%= link_to "Secret Code's", secret_code_index_path, class: 'btn btn-warning btn-lg' %>
</br></br>
</div>
  </div>
  <%elsif user_signed_in?%>
  <div class="jumbotron">
    <div class="container">
    	</br></br>
    	Your Email: <%=current_user.email%>
<%if current_user.secret_code_id.to_i!=0
@code = SecretCode.find_by_id(current_user.secret_code_id).code
else
@code= "--"
end%></br></br>
    	Your Secret Code: <%=@code%> 
</div>
  </div>
<%else%>
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome!</h1>
      <p>Login to get started.</p>
      <p>
        <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary btn-lg' %>
      </p>
    </div>
  </div>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestTask</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-inverse" style="     margin-bottom: 0px;!important;">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Test-Task Demo', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.email %>
              <span class="caret"></span>
            </a>
            
          </li><li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>

        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
         
        <% end %>
      </ul>
    </div>
  </div>
</nav>
     <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

<div align="center" style="position:relative;width:100%;background-color: rgba(204, 204, 204, 0.3);" id="appFooter">
	<table width="100%"><tr>
<td align="left" style="padding-left:10px;" height="30px"><a href="javascript:void(0);" title="Home"></a>&nbsp;&nbsp;&nbsp;<span class="footer_wix" >© 2016 Test-Task. All rights reserved.</span></td>

	</tr></table>


</div>
<script type="text/javascript">

if($("body")[0].clientHeight < $("body")[0].scrollHeight){
 

  if($("#appFooter").length>0){
  $("#appFooter").css({"top": ($("body")[0].scrollHeight - $("body")[0].clientHeight) + "px"});
  }
}

</script>




</body>
</html>

app/views/secret_code/add_secret_code.html.erb
<div class="jumbotron">
<div class="container">




</div>
</div>

app/views/secret_code/index.html.erb
<div class="jumbotron">
<div class="container">
</br>
<%= form_for('secret_code', as: 'secret_code', url: secret_code_add_path) do |f| %>

<h2>Add Secret Code(s)!</h2>
Select No.of Secret Code(s) to be added:
<select name="no_of_code" class="code_select">
<option value="1">1</option>
<option value="10">10</option>
<option value="20">20</option>
<option value="50">50</option>
<option value="100">100</option>
</select>
&nbsp;&nbsp;
<%= f.submit "Add Secret Code" , class: 'btn btn-danger btn-lg'%>&nbsp;&nbsp;&nbsp;
<%add_user_path = "/home/add_user"%>
<%= link_to 'Add User', add_user_path, class: 'btn btn-success btn-lg' %>
<%end%>

</br>


<table width="100%" align="center" border='1px'  class="table table-bordered table-admin">
<thead>
<tr class="header_bg">
<th>S.No</th>
<th>Secret Code</th>
<th>User Email</th>
</tr>
</thead>

<tbody>
<%
i=1
@code.each do |c| 
if c.user_id.to_i!=0
@email = User.find_by_id(c.user_id).email
else
@email= "--"
end
%>
<tr class="odd">
<td width="1%" align="center"><%= i %></td>
<td width="12%" style="word-break: break-all;"><%= c.code %></td> 
<td width="12%" style="word-break: break-all;"><%= @email %></td>
</tr>
<%i=i+1 
end %>
</tbody>
</table>
</div>
</div>